### ISSUE TITLE
allow varaible to accept HASH and ARRAY values.

### ISSUE THREAD

**Issue by oetiker** [maettu/Data-Structure-Validation#3]
I have a config variable without any further definition as to the nature of its content:

```perl
probe_cfg => {
      description => 'dummy entry. this will be replaces once the probe is loaded',
}
````

I would expect it to accept any content whatsoever, including ARRAY and HASH references without
complaints.

The use case is, that I will launch another instance of the validator to verify the content of the probe_cfg once the respective probe object is loaded.

**Comment by maettu** [comment]
Why is this not ok?

 my $schema = {
    probe_cfg => {
    }
 };

 my $config = {
    probe_cfg => 'dummy entry.'

 };

**Comment by oetiker** [comment]
should work
```perl
my $schema = {
    probe_cfg => {
    }
};

my $config = {
    probe_cfg => { some_fancy => [ 'dummy entry.'] }
};
````

**Comment by maettu** [comment]
now skipping config branches if schema key is empty: https://github.com/maettu/Data-Structure-Validation/commit/e6f412430d21552bce985122bc72b01419ff494e
