### ISSUE TITLE
transformer missing

### ISSUE THREAD

**Issue by oetiker** [maettu/Data-Structure-Validation#4]
if a transformer property is present, it is called with the (value,section) what it returns is stored in the value. If the transformer is unhappy, it should throw an exception which gets caught by the Validation module. eg:

```perl
my $timespecfactor = {
    d => 24*3600,
    m => 60,
    s => 1,
    h => 3600
};

my $transformer = sub {
    my ($value,$section) = shift;
    if (defined $value && $value =~ /(\d+)([dmsh]?)/){
         return ($1 * $timespecfactor->{($2 || 's')});
     }
     $validator->transform_exception('Expected a number of seconds or a number followed by [dhms]');
 };
```

**Comment by maettu** [comment]
Atm I think transforming should not be part of a validation module.
We should either rename the thing to "Data-Structure-Processor" or make a (pre-)transformer module /methinks.

**Comment by oetiker** [comment]
no problem with changeing the name :)

**Comment by maettu** [comment]
in
